repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff          # linter
        args: [--fix]
      - id: ruff-format   # formatter
  - repo: local
    hooks:
      - id: check-from-imports
        name: Ban from-imports for everything except relative imports
        entry: scripts/check-imports
        language: python
        types: [python]
