"""unique_identity_name

Revision ID: e2b2f7167f7a
Revises: a398808a9d40
Create Date: 2026-07-21 08:43:51.504761

"""

import alembic.op as op

# revision identifiers, used by Alembic.
revision: str = "e2b2f7167f7a"
down_revision: str | None = "a398808a9d40"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("identity", schema=None) as batch_op:
        batch_op.create_unique_constraint("uix_identity_name", ["name"])

    # ### end Alembic commands ###
