"""unique_role_member

Revision ID: c5d2f8b3e7g4
Revises: b4c1e9a2f6d3
Create Date: 2026-08-20 11:00:00.000000

"""

import alembic.op as op

# revision identifiers, used by Alembic.
revision: str = "c5d2f8b3e7g4"
down_revision: str | None = "b4c1e9a2f6d3"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role_member", schema=None) as batch_op:
        batch_op.create_unique_constraint("uix_role_id_identity_id", ["role_id", "identity_id"])

    # ### end Alembic commands ###
