"""baseline tenant schema

Revision ID: a398808a9d40
Revises:
Create Date: 2026-06-21 15:25:40.443106

"""

import alembic.op as op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a398808a9d40"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("by_identity_id", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("idx_audit_log_at", ["at"], unique=False)
        batch_op.create_index("idx_audit_log_by_identity_id", ["by_identity_id"], unique=False)
        batch_op.create_index("idx_audit_log_type", ["type"], unique=False)

    op.create_table(
        "auth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("client_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("tag_id_list", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("config", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "client_type"),
    )
    with op.batch_alter_table("auth", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_name"), ["name"], unique=False)

    op.create_table(
        "bastion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("ssh_proxy_jump", sa.String(), nullable=True),
        sa.Column("tag_id_list", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "boundary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("ceiling_list", sa.JSON(), nullable=True),
        sa.Column("denied_list", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_table("default", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_table(
        "identity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "identity_account_key",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("public_key", sa.JSON(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.Integer(), nullable=True),
    )
    with op.batch_alter_table("identity_account_key", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_identity_account_key_id"), ["id"], unique=True)

    op.create_table(
        "identity_boundary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("boundary_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_id", "boundary_id", name="uix_identity_id_boundary_id"),
    )
    op.create_table(
        "identity_invitation_key",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key", sa.LargeBinary(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.Integer(), nullable=True),
        sa.Column("accepted_at", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("is_accepted", sa.Boolean(), nullable=False),
        sa.Column("accepted_public_key_id", sa.String(), nullable=True),
    )
    with op.batch_alter_table("identity_invitation_key", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_identity_invitation_key_id"), ["id"], unique=True)

    op.create_table(
        "identity_session_key",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("public_key", sa.JSON(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("login_ip", sa.String(), nullable=True),
    )
    with op.batch_alter_table("identity_session_key", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_identity_session_key_id"), ["id"], unique=True)

    op.create_table(
        "identity_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_id", "tag_id", name="uix_identity_id_tag_id"),
    )
    op.create_table(
        "oauth2_login_request",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_key_thumbprint", sa.String(), nullable=False),
        sa.Column("session_public_key", sa.JSON(), nullable=False),
        sa.Column("auth_config_id", sa.Integer(), nullable=False),
        sa.Column("code_verifier", sa.LargeBinary(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("client_redirect_uri", sa.String(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oidc_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("private_key", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.JSON(), nullable=False),
        sa.Column("valid_after", sa.Integer(), nullable=False),
        sa.Column("valid_before", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("oidc_key", schema=None) as batch_op:
        batch_op.create_index("idx_oidc_key_valid", ["valid_before", "valid_after"], unique=False)

    op.create_table(
        "public_key_denylist",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
    )
    with op.batch_alter_table("public_key_denylist", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_public_key_denylist_id"), ["id"], unique=True)

    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("grant_list", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "role_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signing_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("key", sa.LargeBinary(), nullable=False),
        sa.Column("serial_number", sa.Integer(), nullable=False),
        sa.Column("valid_after", sa.Integer(), nullable=False),
        sa.Column("valid_before", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("signing_key", schema=None) as batch_op:
        batch_op.create_index("idx_valid_before_valid_after", ["valid_before", "valid_after"], unique=False)

    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "value", name="uix_name_value"),
        sqlite_autoincrement=True,
    )
    # ### end Alembic commands ###
