"""unique_role_boundary_name

Revision ID: b4c1e9a2f6d3
Revises: d6a2f4c8e910
Create Date: 2026-08-20 10:00:00.000000

"""

import alembic.op as op

# revision identifiers, used by Alembic.
revision: str = "b4c1e9a2f6d3"
down_revision: str | None = "d6a2f4c8e910"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.create_unique_constraint("uix_role_name", ["name"])

    with op.batch_alter_table("boundary", schema=None) as batch_op:
        batch_op.create_unique_constraint("uix_boundary_name", ["name"])

    # ### end Alembic commands ###
