openapi: 3.1.0
info:
  title: IDB API implementation
  description: IDB API to control users and hosts
  version: '1.0'

x-bundles:
  invitation-signature: &InvitationSignature
    - HMACSignature: []
      ED25519Signature: []
    - HMACSignature: []
      ECDSASignature: []
  identity-signature: &AccountSignature
    - ED25519Signature: []
    - ECDSASignature: []
  session-signature: &SessionSignature
    - ED25519Signature: []
    - ECDSASignature: []

servers:
  - url: https://api.example.com/idb
    description: IDB directory base path

components:
  securitySchemes:

    HMACSignature:
      type: http
      scheme: signature
      description: >
        Signatures are generated according to RFC 9421 via hmac-sha256.
        The signature must be included in the `Signature` and `Signature-Input`
        headers.
      x-signatureAlgorithm: hmac-sha256

    ED25519Signature:
      type: http
      scheme: signature
      description: >
        Signatures are generated according to RFC 9421 via ed25519.
        The signature must be included in the `Signature` and `Signature-Input`
        headers.
      x-signatureAlgorithm: ed25519

    ECDSASignature:
      type: http
      scheme: signature
      description: >
        Signatures are generated according to RFC 9421 via ecdsa-p256-sha256.
        The signature must be included in the `Signature` and `Signature-Input`
        headers.
      x-signatureAlgorithm: ecdsa-p256-sha256

  schemas:
    ProblemDocument:
      type: object
      required: [type]
      additionalProperties: false
      properties:
        type:
          type: string
          enum:
            - about:blank
        detail:
          type: string
        title:
          type: string
        status:
          type: integer

    Directory:
      type: object
      required: [initialize]
      additionalProperties: false
      properties:
        initialize:
          type: string
        accept-invitation:
          type: string
        login:
          type: string
        boundary:
          type: string
        tag:
          type: string


    ECDSAPublicJWK:
      description: RFC 7517
      type: object
      required: [crv, kty, x, y]
      additionalProperties: false
      properties:
        crv:
          type: string
          enum: [P-256]
        kty:
          type: string
          enum: [EC]
        x:
          type: string
        y:
          type: string

    ED25519PublicJWK:
      description: RFC 8037
      type: object
      required: [crv, kty, x]
      additionalProperties: false
      properties:
        crv:
          type: string
          enum: [Ed25519]
        kty:
          type: string
          enum: [OKP]
        x:
          type: string

    PublicJWK:
      description: >
        We currently support only two types because we do not need to support
        more. Patches to suport alternatives are welcome :)
      oneOf:
        - $ref: '#/components/schemas/ECDSAPublicJWK'
        - $ref: '#/components/schemas/ED25519PublicJWK'

    SymmetricJWK:
      description: A private key represented as a JWK
      type: object
      required: [kty, k]
      additionalProperties: false
      properties:
        kty:
          type: string
          enum: [oct]
        k:
          description: base64url encoded symmetric key bytes
          type: string

    PermissionObjectFieldsWithName:
      type: array
      maxItems: 1
      items:
        type: object
        required: [name, value]
        additionalProperties: false
        properties:
          name:
            type: string
            enum: ['name']
          value:
            type: string

    PermissionObjectFieldsWithNameAndTagAndCreatedBy:
      type: array
      items:
        type: object
        required: [name, value]
        additionalProperties: false
        properties:
          name:
            type: string
            enum: ['name', 'tag', 'created_by']
          value:
            type: string


    EmptyList:
      type: array
      maxItems: 0
      items:
        type: "null"

    CRDPermission:
      type: object
      required: [action, action_fields]
      properties:
        action:
          type: string
          enum: ['*', 'create', 'read', 'delete']
        action_fields:
          $ref: '#/components/schemas/EmptyList'

    UPermission:
      type: object
      required: [action, action_fields]
      properties:
        action:
          type: string
          enum: ['update']
        action_fields:
          type: array
          maxItems: 1
          items:
            type: object
            required: ['name', 'value']
            additionalProperties: false
            properties:
              name:
                type: string
                enum: ['field']
              value:
                type: string

    CRUDPermission:
      oneOf:
        - $ref: '#/components/schemas/CRDPermission'
        - $ref: '#/components/schemas/UPermission'

    SimplePermission:
      unevaluatedProperties: false
      anyOf:
        - $ref: '#/components/schemas/CRUDPermission'
        - type: object
          required: [object, action, object_fields, action_fields]
          properties:
            object:
              type: string
              enum: ['boundary', 'tag', 'role']
            object_fields:
              $ref: '#/components/schemas/PermissionObjectFieldsWithName'

    IdentityPermission:
      type: object
      required: [object, action, object_fields, action_fields]
      properties:
        object:
          type: string
          enum: ['identity']
        action:
          type: string
          enum: ['*', 'read', 'create', 'add-tag', 'del-tag', 'ssh-shell', 'ssh-tunnel', 'ssh-tunnel', 'ssh-exec', 'cert']
        object_fields:
          $ref: '#/components/schemas/PermissionObjectFieldsWithNameAndTagAndCreatedBy'
        action_fields:
          $ref: '#/components/schemas/EmptyList'

    Permission:
      oneOf:
        - $ref: '#/components/schemas/SimplePermission'
        - $ref: '#/components/schemas/IdentityPermission'

    Boundary:
      description: A boundary
      type: object
      required: [id, name, description, ceiling_list, denied_list]
      additionalProperties: false
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        ceiling_list:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
        denied_list:
          type: array
          items:
            $ref: '#/components/schemas/Permission'

    AcceptInvitationRequest:
      type: object
      required: [account_public_key, nonce]
      additionalProperties: false
      properties:
        account_public_key:
          $ref: '#/components/schemas/PublicJWK'
        nonce:
          type: string

    LoginRequest:
      type: object
      required: [session_public_key, nonce]
      additionalProperties: false
      properties:
        session_public_key:
          $ref: '#/components/schemas/PublicJWK'
        nonce:
          type: string

    CreateBoundaryRequest:
      type: object
      required: [name]
      additionalProperties: false
      properties:
        name:
          type: string
        description:
          type: string

    UpdateBoundaryRequest:
      type: object
      additionalProperties: false
      properties:
        description:
          type: string
        denied_list:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
        ceiling_list:
          type: array
          items:
            $ref: '#/components/schemas/Permission'

  responses:
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDocument'

    InitializeResponse:
      description: First identity created
      content:
        application/json:
          schema:
            type: object
            required: [key]
            additionalProperties: false
            properties:
              key:
                $ref: '#/components/schemas/SymmetricJWK'

    BoundaryListResponse:
      description: OK
      content:
        application/json:
          schema:
            type: object
            required: [boundaries]
            additionalProperties: false
            properties:
              boundaries:
                type: array
                items:
                  $ref: '#/components/schemas/Boundary'

    BoundaryResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Boundary'

    AcceptInvitationResponse:
      description: Invitation accepted
      content:
        application/json:
          schema:
            type: object

paths:
  /idb/directory:
    get:
      summary: Directory
      description: The IDB directory
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Directory"

  /idb/initialize:
    post:
      summary: Initialize
      description: Setup the application after first startup
      responses:
        "204":
          description: Allready created
        "200":
          $ref: '#/components/responses/InitializeResponse'

  /idb/accept-invitation:
    post:
      security: *InvitationSignature
      summary: Accept invitation
      description: Bind a local account key with the invitation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptInvitationRequest'
      responses:
        "204":
          description: Invitation accepted
        default:
          $ref: '#/components/responses/ErrorResponse'

  /idb/login:
    post:
      security: *AccountSignature
      summary: Login
      description: >
        Bind a local session key with the identity associated with
        the account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "204":
          description: Login OK
        default:
          $ref: '#/components/responses/ErrorResponse'

  /idb/boundary:
    get:
      security: *SessionSignature
      summary: List Boundaries
      description: >
        Return the list of boundaries the user is allowed to see
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: If specified, return boundaries that match this name
        - in: query
          name: id
          schema:
            type: string
          required: false
          description: If specified, return boundaries that match this id
      responses:
        "200":
          $ref: "#/components/responses/BoundaryListResponse"
        default:
          $ref: '#/components/responses/ErrorResponse'
    post:
      security: *SessionSignature
      summary: Create boundary
      description: >
        Create a new boundary
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBoundaryRequest'
      responses:
        "201":
          $ref: "#/components/responses/BoundaryResponse"
        default:
          $ref: '#/components/responses/ErrorResponse'


  /idb/boundary/{boundary_id}:
    parameters:
      - in: path
        name: boundary_id
        schema:
          type: integer
        required: true
        description: The unique identifier of the boundary requested
    get:
      security: *SessionSignature
      summary: Read one boundary
      description: >
        Details on one boundary
      responses:
        "200":
          $ref: "#/components/responses/BoundaryResponse"
        default:
          $ref: '#/components/responses/ErrorResponse'
    patch:
      security: *SessionSignature
      summary: Update boundary
      description: >
        Update boundary parameters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBoundaryRequest'
      responses:
        "200":
          $ref: "#/components/responses/BoundaryResponse"
        default:
          $ref: '#/components/responses/ErrorResponse'
    delete:
      security: *SessionSignature
      summary: Delete one boundary
      responses:
        "204":
          description: Delete OK
        default:
          $ref: '#/components/responses/ErrorResponse'
