openapi: 3.1.0
info:
  title: ADMIN API implementation
  description: ADMIN API to control users and hosts
  version: '1.0'

servers:
  - url: https://api.example.com/admin
    description: ADMIN directory base path

components:
  schemas:
    ProblemDocument:
      type: object
      required: [type]
      additionalProperties: false
      properties:
        type:
          type: string
          enum:
            - about:blank
        detail:
          type: string
        title:
          type: string
        status:
          type: integer

    Directory:
      type: object
      required: [initialize]
      additionalProperties: false
      properties:
        initialize:
          type: string

  responses:
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDocument'

    InitializeResponse:
      description: First identity created
      content:
        application/json:
          schema:
            type: object
            required: [identity_id, key_id, key]
            additionalProperties: false
            properties:
              identity_id:
                type: string
              key_id:
                type: string
              key:
                type: string


paths:
  /admin/directory:
    get:
      summary: Directory
      description: The ADMIN directory
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Directory"

  /admin/initialize:
    post:
      summary: Initialize
      description: Setup the application after first startup
      responses:
        "204":
          description: Allready created
        "200":
          $ref: '#/components/responses/InitializeResponse'
