#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "openapi-core",
#   "sqlalchemy",
#   "cryptography",
#   "webob",
#   "http-message-signatures",
#   "pytest",
#   "idb",
# ]
# [tool.uv.sources]
# idb = { path = "../", editable = true }
# ///
import argparse
import urllib.parse
import wsgiref.simple_server

import idb.api.app
import idb.api.config

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--config', default='idb.yaml')
    parser.add_argument('-p', '--port', type=int, default=None)
    parser.add_argument('--port-file', default=None)
    args = parser.parse_args()
    server = wsgiref.simple_server.WSGIServer(
        ('127.0.0.1', 0 if args.port is None else args.port),
        wsgiref.simple_server.WSGIRequestHandler
    )
    if args.port_file is not None:
        with open(args.port_file, 'w+') as f:
            f.write(f'{server.server_address[1]}')
    conf = idb.api.config.Config.load(args.config)
    base_url = urllib.parse.urlparse(conf.base_url)
    base_url = base_url._replace(netloc=f'{server.server_address[0]}:{server.server_address[1]}')
    conf.base_url = urllib.parse.urlunparse(base_url)
    app = idb.api.app.create(conf)
    server.set_app(app)
    server.serve_forever()
