#!/usr/bin/env -S uv run -q --script
# /// script
# dependencies = [
#   "openapi-core",
#   "sqlalchemy",
#   "cryptography",
#   "webob",
#   "http-message-signatures",
#   "pytest",
#   "coverage",
#   "gunicorn",
#   "pydantic",
#   "idb",
# ]
# [tool.uv.sources]
# idb = { path = "../", editable = true }
# ///
import os

if __name__ == '__main__':
    cov = None
    if os.environ.get('COVERAGE_PROCESS_START'):
        import coverage
        cov = coverage.Coverage()
        cov.start()

    import idb.api.server
    try:
        idb.api.server.run()
    finally:
        if cov:
            cov.stop()
            cov.save()
