#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "cryptography>=45.0.0",
#   "requests",
#   "http-message-signatures",
#   "tabulate",
#   "pytest",
#   "dateparser",
#   "idb",
# ]
# [tool.uv.sources]
# idb = { path = "../", editable = true }
# ///
import idb.cli.main_cli

if __name__ == '__main__':
    idb.cli.main_cli.main()
