#!/usr/bin/env -S uv run -q --script
# /// script
# dependencies = [
#   "cryptography>=45.0.0",
#   "requests",
#   "http-message-signatures",
#   "tabulate",
#   "pytest",
#   "dateparser",
#   "coverage",
#   "idb",
# ]
# [tool.uv.sources]
# idb = { path = "../", editable = true }
# ///
import os
import sys

if __name__ == '__main__':
    cov = None
    if os.environ.get('COVERAGE_PROCESS_START'):
        import coverage
        cov = coverage.Coverage()
        cov.start()

    import idb.cli.main_cli
    try:
        idb.cli.main_cli.main()
    except:
        if cov:
            cov.stop()
            cov.save()
        raise
    
