#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "requests",
#   "http-message-signatures",
#   "tabulate",
#   "pytest",
#   "idb",
# ]
# [tool.uv.sources]
# idb = { path = "../", editable = true }
# ///
import idb.ctl.main

if __name__ == '__main__':
    idb.ctl.main.main()
