#!/usr/bin/env -S uv run -q --script
# /// script
# dependencies = [
#   "cryptography",
#   "fastapi",
#   "uvicorn",
#   "pytest",
#   "coverage",
#   "pyjwt",
#   "pf",
# ]
# [tool.uv.sources]
# pf = { path = "../", editable = true }
# ///
import os

if __name__ == '__main__':
    cov = None
    if os.environ.get('COVERAGE_PROCESS_START'):
        import coverage
        cov = coverage.Coverage()
        cov.start()

    import pf.bastion.server
    try:
        pf.bastion.server.run()
    finally:
        if cov:
            cov.stop()
            cov.save()
