#!/usr/bin/env -S uv run -q --script
# /// script
# dependencies = [
#   "cryptography>=45.0.0",
#   "requests",
#   "http-message-signatures",
#   "tabulate",
#   "pytest",
#   "dateparser",
#   "coverage",
#   "pf",
#   "pydantic",
# ]
# [tool.uv.sources]
# pf = { path = "../", editable = true }
# ///
import os

if __name__ == '__main__':
    cov = None
    if os.environ.get('COVERAGE_PROCESS_START'):
        import coverage
        cov = coverage.Coverage()
        cov.start()

    import pf.cli.pfa.main
    try:
        pf.cli.pfa.main.pfa()
    finally:
        if cov:
            cov.stop()
            cov.save()
    

