#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "cryptography>=45.0.0",
#   "sqlalchemy",
#   "webob",
#   "idb",
# ]
# [tool.uv.sources]
# idb = { path = "../", editable = true }
# ///
import idb.api.rotate

if __name__ == '__main__':
    idb.api.rotate.main()
