#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "cryptography>=45.0.0",
#   "sqlalchemy",
#   "webob",
#   "coverage",
#   "pf",
# ]
# [tool.uv.sources]
# pf = { path = "../", editable = true }
# ///
import os

if __name__ == '__main__':
    cov = None
    if os.environ.get('COVERAGE_PROCESS_START'):
        import coverage
        cov = coverage.process_startup()

    import pf.api.rotate
    try:
        pf.api.rotate.main()
    except:
        if cov:
            cov.stop()
            cov.save()
        raise
